# Generated by Django 5.1.4 on 2025-01-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
