# Generated by Django 5.1.4 on 2025-01-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
